In [2]:
import pandas as pd

df = pd.read_csv("../data/bengaluru_house_prices.csv")

In [3]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(529)

In [5]:
df.dtypes

area_type           str
availability        str
location            str
size                str
society             str
total_sqft          str
bath            float64
balcony         float64
price           float64
dtype: object

In [6]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 12791 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12791 non-null  str
 1   availability  12791 non-null  str
 2   location      12790 non-null  str
 3   size          12775 non-null  str
 4   society       7463 non-null   str
 5   total_sqft    12791 non-null  str
 6   bath          12718 non-null  float64
 7   balcony       12186 non-null  float64
 8   price         12791 non-null  float64
dtypes: float64(3), str(6)
memory usage: 999.3 KB

In [8]:
df.drop_duplicates(inplace=True)

In [14]:
df["bath"].isnull().sum()
df["bath"].fillna(df["bath"].median())

0        2.0
1        5.0
2        2.0
3        3.0
4        2.0
        ...
13314    3.0
13315    4.0
13316    5.0
13317    2.0
13318    4.0
Name: bath, Length: 12791, dtype: float64

In [12]:
df["balcony"].fillna(df["balcony"].median())

0        1.0
1        3.0
2        3.0
3        1.0
4        1.0
        ...
13314    3.0
13315    0.0
13316    2.0
13317    1.0
13318    1.0
Name: balcony, Length: 12791, dtype: float64

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 12791 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12791 non-null  str
 1   availability  12791 non-null  str
 2   location      12790 non-null  str
 3   size          12775 non-null  str
 4   society       7463 non-null   str
 5   total_sqft    12791 non-null  str
 6   bath          12718 non-null  float64
 7   balcony       12186 non-null  float64
 8   price         12791 non-null  float64
dtypes: float64(3), str(6)
memory usage: 999.3 KB

In [17]:
df.dropna(subset=["location"], inplace=True)

In [ ]:
df["size"]=df["size"].str.strip("BHK")
df["size"]=df["size"].str.strip("Bedroom")
df["size"]=df["size"].str.strip("Room")
df["size"].unique()
df["size"]=df["size"].astype("float")

In [29]:
df["size"]=df["size"].fillna(df["size"].median())

In [32]:
df["society"].fillna("Not Available", inplace=True)

C:\Users\rukun\AppData\Local\Temp\ipykernel_25308\1911120935.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["society"].fillna("Not Available", inplace=True)

0              Coomee
1              Theanmp
2        Not Available
3              Soiewre
4        Not Available
             ...
13314          SoosePr
13315          ArsiaEx
13316    Not Available
13317          Mahla T
13318          SollyCl
Name: society, Length: 12790, dtype: str

In [33]:
df.info()

<class 'pandas.DataFrame'>
Index: 12790 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12790 non-null  str
 1   availability  12790 non-null  str
 2   location      12790 non-null  str
 3   size          12790 non-null  float64
 4   society       7462 non-null   str
 5   total_sqft    12790 non-null  str
 6   bath          12717 non-null  float64
 7   balcony       12185 non-null  float64
 8   price         12790 non-null  float64
dtypes: float64(4), str(5)
memory usage: 999.2 KB

In [ ]:

df["society"].count()

df["society"].fillna("unknown")
df["society"].isnull().sum()

np.int64(5328)

In [49]:
df["bath"] = df["bath"].fillna(df["bath"].median())

In [50]:
df["balcony"] = df["balcony"].fillna(0)

In [51]:
df.info()

<class 'pandas.DataFrame'>
Index: 12790 entries, 0 to 13318
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     12790 non-null  str
 1   availability  12790 non-null  str
 2   location      12790 non-null  str
 3   size          12790 non-null  float64
 4   society       12790 non-null  str
 5   total_sqft    12790 non-null  str
 6   bath          12790 non-null  float64
 7   balcony       12790 non-null  float64
 8   price         12790 non-null  float64
dtypes: float64(4), str(5)
memory usage: 999.2 KB

In [ ]:
df["total_sqft"].unique()
def convert_sqft(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

df["total_sqft"] = df["total_sqft"].apply(convert_sqft)

In [56]:
df = df.dropna(subset=["total_sqft"])

In [63]:
df["price_per_sqft"] = (df["price"] * 100000) / df["total_sqft"]
df.rename(columns={"size": "bhk"}, inplace=True)
df

,area_type,availability,location,bhk,society,total_sqft,bath,balcony,price,price_per_sqft
0,Super built-up Area,19-Dec,Electronic City Phase II,2.0,Coomee,1056.0,2.0,1.0,39.07,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4.0,Theanmp,2600.0,5.0,3.0,120.00,4615.384615
2,Built-up Area,Ready To Move,Uttarahalli,3.0,Unknown,1440.0,2.0,3.0,62.00,4305.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3.0,Soiewre,1521.0,3.0,1.0,95.00,6245.890861
4,Super built-up Area,Ready To Move,Kothanur,2.0,Unknown,1200.0,2.0,1.0,51.00,4250.000000
...,...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3.0,SoosePr,1715.0,3.0,3.0,112.00,6530.612245
13315,Built-up Area,Ready To Move,Whitefield,5.0,ArsiaEx,3453.0,4.0,0.0,231.00,6689.834926
13316,Super built-up Area,Ready To Move,Richards Town,4.0,Unknown,3600.0,5.0,0.0,400.00,11111.111111
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2.0,Mahla T,1141.0,2.0,1.0,60.00,5258.545136
13318,Super built-up Area,18-Jun,Padmanabhanagar,4.0,SollyCl,4689.0,4.0,1.0,488.00,10407.336319

In [66]:
df.to_csv("../data/cleaned_house_prices.csv", index=False)